"""Initial schema

Revision ID: 858417da6351
Revises: 
Create Date: 2026-02-26 11:41:29.584916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '858417da6351'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create PostgreSQL enums with idempotent pattern matching docs/the_lab_v0_5.sql
    # This ensures re-running migrations doesn't fail if enums already exist
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE cycle_types AS ENUM ('microcycle', 'mesocycle', 'macrocycle');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE quantity_units AS ENUM (
                'repetitions', 'meters', 'feet', 'miles', 'kilometers', 'yards',
                'seconds', 'minutes', 'hours'
            );
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE cadence_units AS ENUM (
                'strokes_per_minute', 'steps_per_minute', 'revolutions_per_minute'
            );
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE sides AS ENUM ('right', 'left');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE carry_styles AS ENUM (
                'vest', 'suitcase_double', 'suitcase_single', 'carry_double',
                'carry_single', 'front_rack', 'other'
            );
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE external_load_units AS ENUM (
                'lbs', 'kilograms', 'bodyweight', 'percent_1rm'
            );
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE pace_units AS ENUM ('per_mile', 'per_kilometer', 'per_500m');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE energy_units AS ENUM ('calories', 'watts');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE set_types AS ENUM ('strength', 'endurance', 'other');
        EXCEPTION WHEN duplicate_object THEN NULL; END $$;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('implements',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_implements')),
    sa.UniqueConstraint('name', name='implements_name_uk')
    )
    op.create_table('movements',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movements')),
    sa.UniqueConstraint('name', name='movements_name_uk')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name='users_username_uk')
    )
    op.create_table('variation_types',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variation_types')),
    sa.UniqueConstraint('name', name='variation_types_name_uk')
    )
    op.create_table('cycles',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', postgresql.ENUM('microcycle', 'mesocycle', 'macrocycle', name='cycle_types', create_type=False), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('start_date IS NULL OR end_date IS NULL OR end_date >= start_date', name=op.f('ck_cycles_dates_ck')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cycles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cycles'))
    )
    op.create_table('dailies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('protein', sa.Integer(), nullable=True),
    sa.Column('sleep', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.CheckConstraint('protein IS NULL OR protein >= 0', name=op.f('ck_dailies_protein_ck')),
    sa.CheckConstraint('sleep IS NULL OR (sleep >= 0 AND sleep <= 24)', name=op.f('ck_dailies_sleep_ck')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_dailies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dailies')),
    sa.UniqueConstraint('user_id', 'date', name='dailies_user_date_uk')
    )
    op.create_table('goals',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('achieved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('date_set', sa.Date(), nullable=True),
    sa.Column('date_achieved', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('date_set IS NULL OR date_achieved IS NULL OR date_achieved >= date_set', name=op.f('ck_goals_dates_ck')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_goals_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goals'))
    )
    op.create_table('injuries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('injury_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_resolution', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.CheckConstraint('injury_date IS NULL OR full_resolution IS NULL OR full_resolution >= injury_date', name=op.f('ck_injuries_dates_ck')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_injuries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injuries'))
    )
    op.create_table('notes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("entry_date >= DATE '1900-01-01'", name=op.f('ck_notes_entry_date_ck')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index('idx_notes_user_date', 'notes', ['user_id', 'entry_date'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('training_zeal', sa.Integer(), nullable=True),
    sa.Column('fatigue_concluding', sa.Integer(), nullable=True),
    sa.Column('fed', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('fatigue_concluding IS NULL OR (fatigue_concluding >= 1 AND fatigue_concluding <= 10)', name=op.f('ck_sessions_fatigue_ck')),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR end_time >= start_time', name=op.f('ck_sessions_times_ck')),
    sa.CheckConstraint('training_zeal IS NULL OR (training_zeal >= 1 AND training_zeal <= 10)', name=op.f('ck_sessions_training_zeal_ck')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('variations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('variation_type_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['variation_type_id'], ['variation_types.id'], name=op.f('fk_variations_variation_type_id_variation_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_variations')),
    sa.UniqueConstraint('variation_type_id', 'name', name='variations_type_name_uk')
    )
    op.create_table('cycle_notes',
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], name=op.f('fk_cycle_notes_cycle_id_cycles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_cycle_notes_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cycle_id', 'note_id', name=op.f('pk_cycle_notes'))
    )
    op.create_index('idx_cycle_notes_note', 'cycle_notes', ['note_id'], unique=False)
    op.create_table('goal_notes',
    sa.Column('goal_id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name=op.f('fk_goal_notes_goal_id_goals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_goal_notes_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id', 'note_id', name=op.f('pk_goal_notes'))
    )
    op.create_index('idx_goal_notes_note', 'goal_notes', ['note_id'], unique=False)
    op.create_table('injury_notes',
    sa.Column('injury_id', sa.BigInteger(), nullable=False),
    sa.Column('note_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['injury_id'], ['injuries.id'], name=op.f('fk_injury_notes_injury_id_injuries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_injury_notes_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('injury_id', 'note_id', name=op.f('pk_injury_notes'))
    )
    op.create_index('idx_injury_notes_note', 'injury_notes', ['note_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('order_in_session', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hr_avg', sa.Integer(), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('(hr_avg IS NULL OR hr_avg > 0) AND (hr_max IS NULL OR hr_max > 0)', name=op.f('ck_modules_hr_ck')),
    sa.CheckConstraint('order_in_session >= 1', name=op.f('ck_modules_order_ck')),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR end_time >= start_time', name=op.f('ck_modules_times_ck')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_modules_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules')),
    sa.UniqueConstraint('session_id', 'order_in_session', name='session_order_uk')
    )
    op.create_table('sets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('order_in_module', sa.Integer(), nullable=False),
    sa.Column('set_type', postgresql.ENUM('strength', 'endurance', 'other', name='set_types', create_type=False), server_default='strength', nullable=False),
    sa.Column('parent_set_id', sa.BigInteger(), nullable=True),
    sa.Column('rest_period_prior_seconds', sa.Integer(), nullable=True),
    sa.Column('hr_avg', sa.Integer(), nullable=True),
    sa.Column('hr_min', sa.Integer(), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint('(hr_avg IS NULL OR hr_avg > 0) AND (hr_min IS NULL OR hr_min > 0) AND (hr_max IS NULL OR hr_max > 0)', name=op.f('ck_sets_hr_ck')),
    sa.CheckConstraint('order_in_module >= 1', name=op.f('ck_sets_order_ck')),
    sa.CheckConstraint('rest_period_prior_seconds IS NULL OR rest_period_prior_seconds >= 0', name=op.f('ck_sets_rest_ck')),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_sets_module_id_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_set_id'], ['sets.id'], name=op.f('fk_sets_parent_set_id_sets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sets')),
    sa.UniqueConstraint('module_id', 'order_in_module', name='module_order_uk')
    )
    op.create_index('idx_sets_module_order', 'sets', ['module_id', 'order_in_module'], unique=False)
    op.create_index('idx_sets_parent', 'sets', ['parent_set_id'], unique=False)
    op.create_table('endurance_set_details',
    sa.Column('set_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantity_unit', postgresql.ENUM('repetitions', 'meters', 'feet', 'miles', 'kilometers', 'yards', 'seconds', 'minutes', 'hours', name='quantity_units', create_type=False), nullable=True),
    sa.Column('average_cadence', sa.Integer(), nullable=True),
    sa.Column('cadence_unit', postgresql.ENUM('strokes_per_minute', 'steps_per_minute', 'revolutions_per_minute', name='cadence_units', create_type=False), nullable=True),
    sa.Column('pace_seconds', sa.Integer(), nullable=True),
    sa.Column('pace_unit', postgresql.ENUM('per_mile', 'per_kilometer', 'per_500m', name='pace_units', create_type=False), nullable=True),
    sa.Column('energy_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('energy_unit', postgresql.ENUM('calories', 'watts', name='energy_units', create_type=False), nullable=True),
    sa.Column('external_load_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('external_load_unit', postgresql.ENUM('lbs', 'kilograms', 'bodyweight', 'percent_1rm', name='external_load_units', create_type=False), nullable=True),
    sa.Column('carry_style', postgresql.ENUM('vest', 'suitcase_double', 'suitcase_single', 'carry_double', 'carry_single', 'front_rack', 'other', name='carry_styles', create_type=False), nullable=True),
    sa.CheckConstraint('average_cadence IS NULL OR average_cadence >= 0', name=op.f('ck_endurance_set_details_cadence_ck')),
    sa.CheckConstraint('energy_value IS NULL OR energy_value >= 0', name=op.f('ck_endurance_set_details_energy_ck')),
    sa.CheckConstraint('external_load_value IS NULL OR external_load_value >= 0', name=op.f('ck_endurance_set_details_load_ck')),
    sa.CheckConstraint('pace_seconds IS NULL OR pace_seconds >= 0', name=op.f('ck_endurance_set_details_pace_ck')),
    sa.CheckConstraint('quantity_value IS NULL OR quantity_value >= 0', name=op.f('ck_endurance_set_details_quantity_ck')),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name=op.f('fk_endurance_set_details_set_id_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', name=op.f('pk_endurance_set_details'))
    )
    op.create_table('set_variations',
    sa.Column('set_id', sa.BigInteger(), nullable=False),
    sa.Column('variation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name=op.f('fk_set_variations_set_id_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variation_id'], ['variations.id'], name=op.f('fk_set_variations_variation_id_variations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', 'variation_id', name=op.f('pk_set_variations'))
    )
    op.create_index('idx_set_variations_set', 'set_variations', ['set_id'], unique=False)
    op.create_index('idx_set_variations_variation', 'set_variations', ['variation_id'], unique=False)
    op.create_table('strength_set_details',
    sa.Column('set_id', sa.BigInteger(), nullable=False),
    sa.Column('movement_id', sa.BigInteger(), nullable=False),
    sa.Column('implement_id', sa.BigInteger(), nullable=True),
    sa.Column('external_load_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('external_load_unit', postgresql.ENUM('lbs', 'kilograms', 'bodyweight', 'percent_1rm', name='external_load_units', create_type=False), nullable=True),
    sa.Column('external_load_desc', sa.String(length=256), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('intensity_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tempo', sa.String(length=8), nullable=True),
    sa.Column('myo_reps_count', sa.Integer(), nullable=True),
    sa.Column('cheated_count', sa.Integer(), nullable=True),
    sa.Column('negatives_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('(myo_reps_count IS NULL OR myo_reps_count >= 0) AND (cheated_count IS NULL OR cheated_count >= 0) AND (negatives_count IS NULL OR negatives_count >= 0)', name=op.f('ck_strength_set_details_counts_ck')),
    sa.CheckConstraint('external_load_value IS NULL OR external_load_value >= 0', name=op.f('ck_strength_set_details_load_ck')),
    sa.CheckConstraint('intensity_percentage IS NULL OR (intensity_percentage >= 0 AND intensity_percentage <= 100)', name=op.f('ck_strength_set_details_intensity_ck')),
    sa.CheckConstraint('reps IS NULL OR reps >= 0', name=op.f('ck_strength_set_details_reps_ck')),
    sa.CheckConstraint('rir IS NULL OR (rir >= 0 AND rir <= 10)', name=op.f('ck_strength_set_details_rir_ck')),
    sa.ForeignKeyConstraint(['implement_id'], ['implements.id'], name=op.f('fk_strength_set_details_implement_id_implements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], name=op.f('fk_strength_set_details_movement_id_movements'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], name=op.f('fk_strength_set_details_set_id_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('set_id', name=op.f('pk_strength_set_details'))
    )
    op.create_index('idx_strength_movement', 'strength_set_details', ['movement_id'], unique=False)
    op.create_index('idx_strength_movement_implement', 'strength_set_details', ['movement_id', 'implement_id'], unique=False)
    op.create_index('idx_strength_rir', 'strength_set_details', ['rir'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_strength_rir', table_name='strength_set_details')
    op.drop_index('idx_strength_movement_implement', table_name='strength_set_details')
    op.drop_index('idx_strength_movement', table_name='strength_set_details')
    op.drop_table('strength_set_details')
    op.drop_index('idx_set_variations_variation', table_name='set_variations')
    op.drop_index('idx_set_variations_set', table_name='set_variations')
    op.drop_table('set_variations')
    op.drop_table('endurance_set_details')
    op.drop_index('idx_sets_parent', table_name='sets')
    op.drop_index('idx_sets_module_order', table_name='sets')
    op.drop_table('sets')
    op.drop_table('modules')
    op.drop_index('idx_injury_notes_note', table_name='injury_notes')
    op.drop_table('injury_notes')
    op.drop_index('idx_goal_notes_note', table_name='goal_notes')
    op.drop_table('goal_notes')
    op.drop_index('idx_cycle_notes_note', table_name='cycle_notes')
    op.drop_table('cycle_notes')
    op.drop_table('variations')
    op.drop_table('sessions')
    op.drop_index('idx_notes_user_date', table_name='notes')
    op.drop_table('notes')
    op.drop_table('injuries')
    op.drop_table('goals')
    op.drop_table('dailies')
    op.drop_table('cycles')
    op.drop_table('variation_types')
    op.drop_table('users')
    op.drop_table('movements')
    op.drop_table('implements')
    # ### end Alembic commands ###

    # Drop PostgreSQL enums
    op.execute("DROP TYPE IF EXISTS set_types CASCADE")
    op.execute("DROP TYPE IF EXISTS energy_units CASCADE")
    op.execute("DROP TYPE IF EXISTS pace_units CASCADE")
    op.execute("DROP TYPE IF EXISTS external_load_units CASCADE")
    op.execute("DROP TYPE IF EXISTS carry_styles CASCADE")
    op.execute("DROP TYPE IF EXISTS sides CASCADE")
    op.execute("DROP TYPE IF EXISTS cadence_units CASCADE")
    op.execute("DROP TYPE IF EXISTS quantity_units CASCADE")
    op.execute("DROP TYPE IF EXISTS cycle_types CASCADE")
