-- The Lab (v0.5) - Postgres DDL (with CHECK constraints)
-- Updates from v0.3:
--   * Remove strength_set_details ar_* fields (opaque prefix)
--   * Add unified journal notes table + entity-specific join tables (Option A)
--   * Add carry_styles enum + endurance external load fields
--   * Keep Goals/Cycles independent; both may have overlapping timeframes

BEGIN;

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------

DO $$ BEGIN
  CREATE TYPE cycle_types AS ENUM ('microcycle', 'mesocycle', 'macrocycle');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE quantity_units AS ENUM (
    'repetitions',
    'meters',
    'feet',
    'miles',
    'kilometers',
    'yards',
    'seconds',
    'minutes',
    'hours'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE cadence_units AS ENUM ('strokes_per_minute', 'steps_per_minute', 'revolutions_per_minute');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE sides AS ENUM ('right', 'left');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE carry_styles AS ENUM (
    'vest',
    'suitcase_double',
    'suitcase_single',
    'carry_double',
    'carry_single',
    'front_rack',
    'other'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE external_load_units AS ENUM (
    'lbs',
    'kilograms',
    'bodyweight',
    'percent_1rm'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE pace_units AS ENUM ('per_mile', 'per_kilometer', 'per_500m');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE energy_units AS ENUM ('calories', 'watts');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE set_types AS ENUM ('strength', 'endurance', 'other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- -----------------------------------------------------------------------------
-- Core entities
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username      varchar(128) NOT NULL,
  role          varchar(64),
  created_at    timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT users_username_uk UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS dailies (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date      date NOT NULL,
  user_id   bigint NOT NULL,
  protein   integer,
  sleep     numeric(5,2),

  CONSTRAINT dailies_user_date_uk UNIQUE (user_id, date),
  CONSTRAINT dailies_protein_ck CHECK (protein IS NULL OR protein >= 0),
  CONSTRAINT dailies_sleep_ck   CHECK (sleep IS NULL OR (sleep >= 0 AND sleep <= 24))
);

CREATE TABLE IF NOT EXISTS cycles (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     bigint NOT NULL,
  type        cycle_types,
  start_date  date,
  end_date    date,
  title       varchar(256),
  notes       text,

  CONSTRAINT cycles_dates_ck CHECK (
    start_date IS NULL OR end_date IS NULL OR end_date >= start_date
  )
);

CREATE TABLE IF NOT EXISTS goals (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        bigint NOT NULL,
  title          varchar(256) NOT NULL,
  achieved       boolean NOT NULL DEFAULT false,
  date_set       date,
  date_achieved  date,
  notes          text,

  CONSTRAINT goals_dates_ck CHECK (
    date_set IS NULL OR date_achieved IS NULL OR date_achieved >= date_set
  )
);

CREATE TABLE IF NOT EXISTS injuries (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         bigint NOT NULL,
  injury_date     timestamptz,
  full_resolution timestamptz,
  title           varchar(256) NOT NULL,

  CONSTRAINT injuries_dates_ck CHECK (
    injury_date IS NULL OR full_resolution IS NULL OR full_resolution >= injury_date
  )
);


-- -----------------------------------------------------------------------------
-- Journal notes (Option A): one notes table + entity-specific join tables
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS notes (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    bigint NOT NULL,
  entry_date date NOT NULL,
  title      text,
  body       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT notes_entry_date_ck CHECK (entry_date >= DATE '1900-01-01')
);

CREATE TABLE IF NOT EXISTS goal_notes (
  goal_id bigint NOT NULL,
  note_id bigint NOT NULL,
  PRIMARY KEY (goal_id, note_id)
);

CREATE TABLE IF NOT EXISTS cycle_notes (
  cycle_id bigint NOT NULL,
  note_id  bigint NOT NULL,
  PRIMARY KEY (cycle_id, note_id)
);

CREATE TABLE IF NOT EXISTS injury_notes (
  injury_id bigint NOT NULL,
  note_id   bigint NOT NULL,
  PRIMARY KEY (injury_id, note_id)
);


-- -----------------------------------------------------------------------------
-- Sessions / Modules
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sessions (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id            bigint NOT NULL,
  start_time         timestamptz,
  end_time           timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  training_zeal      integer,
  fatigue_concluding integer,
  fed                boolean,
  notes              text,

  CONSTRAINT sessions_times_ck CHECK (
    start_time IS NULL OR end_time IS NULL OR end_time >= start_time
  ),
  CONSTRAINT sessions_training_zeal_ck CHECK (
    training_zeal IS NULL OR (training_zeal >= 1 AND training_zeal <= 10)
  ),
  CONSTRAINT sessions_fatigue_ck CHECK (
    fatigue_concluding IS NULL OR (fatigue_concluding >= 1 AND fatigue_concluding <= 10)
  )
);

CREATE TABLE IF NOT EXISTS modules (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id        bigint NOT NULL,
  order_in_session  integer NOT NULL,
  start_time        timestamptz,
  end_time          timestamptz,
  hr_avg            integer,
  hr_max            integer,
  notes             text,

  CONSTRAINT modules_order_ck CHECK (order_in_session >= 1),
  CONSTRAINT modules_times_ck CHECK (
    start_time IS NULL OR end_time IS NULL OR end_time >= start_time
  ),
  CONSTRAINT modules_hr_ck CHECK (
    (hr_avg IS NULL OR hr_avg > 0) AND (hr_max IS NULL OR hr_max > 0)
  ),
  CONSTRAINT modules_session_order_uk UNIQUE (session_id, order_in_session)
);


-- -----------------------------------------------------------------------------
-- Movement catalog
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS movements (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  varchar(256) NOT NULL,

  CONSTRAINT movements_name_uk UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS implements (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  varchar(128) NOT NULL,

  CONSTRAINT implements_name_uk UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS variation_types (
  id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name  varchar(128) NOT NULL,

  CONSTRAINT variation_types_name_uk UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS variations (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variation_type_id bigint NOT NULL,
  name              varchar(256) NOT NULL,

  CONSTRAINT variations_type_name_uk UNIQUE (variation_type_id, name)
);


-- -----------------------------------------------------------------------------
-- Sets (base) + detail tables
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sets (
  id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_id                 bigint NOT NULL,
  order_in_module           integer NOT NULL,
  set_type                  set_types NOT NULL DEFAULT 'strength',
  parent_set_id             bigint,

  rest_period_prior_seconds integer,

  hr_avg                    integer,
  hr_min                    integer,
  hr_max                    integer,

  notes                     text,
  created_at                timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT sets_order_ck CHECK (order_in_module >= 1),
  CONSTRAINT sets_module_order_uk UNIQUE (module_id, order_in_module),
  CONSTRAINT sets_rest_ck CHECK (rest_period_prior_seconds IS NULL OR rest_period_prior_seconds >= 0),
  CONSTRAINT sets_hr_ck CHECK (
    (hr_avg IS NULL OR hr_avg > 0) AND
    (hr_min IS NULL OR hr_min > 0) AND
    (hr_max IS NULL OR hr_max > 0)
  )
);

CREATE TABLE IF NOT EXISTS strength_set_details (
  set_id                 bigint PRIMARY KEY,

  movement_id            bigint NOT NULL,
  implement_id           bigint,

  external_load_value    numeric(10,2),
  external_load_unit     external_load_units,
  external_load_desc     varchar(256),

  reps                   integer,
  rir                    integer,
  intensity_percentage   numeric(5,2),
  tempo                  varchar(8),

  myo_reps_count         integer,
  cheated_count          integer,
  negatives_count        integer,

  CONSTRAINT strength_reps_ck CHECK (reps IS NULL OR reps >= 0),
  CONSTRAINT strength_rir_ck CHECK (rir IS NULL OR (rir >= 0 AND rir <= 10)),
  CONSTRAINT strength_intensity_ck CHECK (intensity_percentage IS NULL OR (intensity_percentage >= 0 AND intensity_percentage <= 100)),
  CONSTRAINT strength_counts_ck CHECK (
    (myo_reps_count IS NULL OR myo_reps_count >= 0) AND
    (cheated_count IS NULL OR cheated_count >= 0) AND
    (negatives_count IS NULL OR negatives_count >= 0)
  ),
  CONSTRAINT strength_load_ck CHECK (
    external_load_value IS NULL OR external_load_value >= 0
  )
);

CREATE TABLE IF NOT EXISTS endurance_set_details (
  set_id              bigint PRIMARY KEY,

  quantity_value      numeric(12,3),
  quantity_unit       quantity_units,

  average_cadence     integer,
  cadence_unit        cadence_units,

  pace_seconds        integer,
  pace_unit           pace_units,

  energy_value        numeric(12,3),
  energy_unit         energy_units,

  -- External load for weighted vest walks and carries
  external_load_value numeric(10,2),
  external_load_unit  external_load_units,
  carry_style         carry_styles,

  CONSTRAINT endurance_quantity_ck CHECK (quantity_value IS NULL OR quantity_value >= 0),
  CONSTRAINT endurance_cadence_ck CHECK (average_cadence IS NULL OR average_cadence >= 0),
  CONSTRAINT endurance_pace_ck CHECK (pace_seconds IS NULL OR pace_seconds >= 0),
  CONSTRAINT endurance_energy_ck CHECK (energy_value IS NULL OR energy_value >= 0),
  CONSTRAINT endurance_load_ck CHECK (external_load_value IS NULL OR external_load_value >= 0)
);

CREATE TABLE IF NOT EXISTS set_variations (
  set_id        bigint NOT NULL,
  variation_id  bigint NOT NULL,
  PRIMARY KEY (set_id, variation_id)
);


-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_sets_module_order ON sets (module_id, order_in_module);
CREATE INDEX IF NOT EXISTS idx_sets_parent ON sets (parent_set_id);

CREATE INDEX IF NOT EXISTS idx_strength_movement ON strength_set_details (movement_id);
CREATE INDEX IF NOT EXISTS idx_strength_movement_implement ON strength_set_details (movement_id, implement_id);
CREATE INDEX IF NOT EXISTS idx_strength_rir ON strength_set_details (rir);

CREATE INDEX IF NOT EXISTS idx_set_variations_set ON set_variations (set_id);
CREATE INDEX IF NOT EXISTS idx_set_variations_variation ON set_variations (variation_id);

CREATE INDEX IF NOT EXISTS idx_notes_user_date ON notes (user_id, entry_date);
CREATE INDEX IF NOT EXISTS idx_goal_notes_note ON goal_notes (note_id);
CREATE INDEX IF NOT EXISTS idx_cycle_notes_note ON cycle_notes (note_id);
CREATE INDEX IF NOT EXISTS idx_injury_notes_note ON injury_notes (note_id);


-- -----------------------------------------------------------------------------
-- Foreign keys
-- -----------------------------------------------------------------------------

ALTER TABLE dailies
  ADD CONSTRAINT fk_dailies_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE cycles
  ADD CONSTRAINT fk_cycles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE goals
  ADD CONSTRAINT fk_goals_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE injuries
  ADD CONSTRAINT fk_injuries_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE notes
  ADD CONSTRAINT fk_notes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE goal_notes
  ADD CONSTRAINT fk_goal_notes_goal FOREIGN KEY (goal_id) REFERENCES goals(id) ON DELETE CASCADE;

ALTER TABLE goal_notes
  ADD CONSTRAINT fk_goal_notes_note FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE;

ALTER TABLE cycle_notes
  ADD CONSTRAINT fk_cycle_notes_cycle FOREIGN KEY (cycle_id) REFERENCES cycles(id) ON DELETE CASCADE;

ALTER TABLE cycle_notes
  ADD CONSTRAINT fk_cycle_notes_note FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE;

ALTER TABLE injury_notes
  ADD CONSTRAINT fk_injury_notes_injury FOREIGN KEY (injury_id) REFERENCES injuries(id) ON DELETE CASCADE;

ALTER TABLE injury_notes
  ADD CONSTRAINT fk_injury_notes_note FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE;

ALTER TABLE sessions
  ADD CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;

ALTER TABLE modules
  ADD CONSTRAINT fk_modules_session FOREIGN KEY (session_id) REFERENCES sessions(id) ON DELETE CASCADE;

ALTER TABLE variations
  ADD CONSTRAINT fk_variations_type FOREIGN KEY (variation_type_id) REFERENCES variation_types(id) ON DELETE RESTRICT;

ALTER TABLE sets
  ADD CONSTRAINT fk_sets_module FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE;

ALTER TABLE sets
  ADD CONSTRAINT fk_sets_parent FOREIGN KEY (parent_set_id) REFERENCES sets(id) ON DELETE SET NULL;

ALTER TABLE strength_set_details
  ADD CONSTRAINT fk_strength_set_details_set FOREIGN KEY (set_id) REFERENCES sets(id) ON DELETE CASCADE;

ALTER TABLE strength_set_details
  ADD CONSTRAINT fk_strength_movement FOREIGN KEY (movement_id) REFERENCES movements(id) ON DELETE RESTRICT;

ALTER TABLE strength_set_details
  ADD CONSTRAINT fk_strength_implement FOREIGN KEY (implement_id) REFERENCES implements(id) ON DELETE SET NULL;

ALTER TABLE endurance_set_details
  ADD CONSTRAINT fk_endurance_set_details_set FOREIGN KEY (set_id) REFERENCES sets(id) ON DELETE CASCADE;

ALTER TABLE set_variations
  ADD CONSTRAINT fk_set_variations_set FOREIGN KEY (set_id) REFERENCES sets(id) ON DELETE CASCADE;

ALTER TABLE set_variations
  ADD CONSTRAINT fk_set_variations_variation FOREIGN KEY (variation_id) REFERENCES variations(id) ON DELETE RESTRICT;

COMMIT;
